Controller
Bossy12/ProductsFromMarketPlace pull request #21
Opened 2020-03-27 16:46 UTC by MariusTarnaru

modified CustomerController, employee.fxml  and create EmployeeController to read all Product fields from database and write in TableView from all users.

2020-03-27 16:53 UTC, sabiutayo submitted a review, later dismissed

2020-03-27 16:57 UTC, stefan2212 requested changes

2020-03-27 16:57 UTC, stefan2212 commented on src/main/java/sample/Controller.java
> +        } else if (userVerifier.userExist(user) && !userVerifier.isUserEmployeeType(user)) {
try to use the database interogation only once.  When you are calling userVerifier.userExists you also use the database

2020-03-27 16:58 UTC, Bossy12 approved these changes

2020-03-28 10:09 UTC, MariusTarnaru commented
- I use ProductDao from TableView;
- i changed caller userVerifier.userExists to query database only once :)

2020-03-28 10:56 UTC, Bossy12 approved these changes

2020-03-28 11:56 UTC, sabiutayo approved these changes

2020-03-28 11:56 UTC, sabiutayo commented on src/main/java/sample/CustomerController.java
> +        quantity.setCellValueFactory(new PropertyValueFactory<>("quantity"));
de ce nu folosesti metodele din productDao  si UserDao

2020-03-30 17:31 UTC, stefan2212 requested changes

2020-03-30 17:31 UTC, stefan2212 commented on src/main/java/sample/CustomerController.java
> +        List<ProductDao> result = products.getAllProducts();
The logic where you bring the products should be in a separate method

2020-03-30 17:31 UTC, stefan2212 commented on src/main/java/sample/EmployeeController.java
> +        List<ProductDao> result = products.getAllProducts();
Same here

2020-04-03 14:05 UTC, Bossy12 approved these changes

2020-04-09 05:28 UTC, stefan2212 approved these changes

2020-04-09 06:04 UTC, merged